// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: workqueue.proto

package workqueue

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkqueueService_Process_FullMethodName     = "/chainguard.workqueue.WorkqueueService/Process"
	WorkqueueService_GetKeyState_FullMethodName = "/chainguard.workqueue.WorkqueueService/GetKeyState"
)

// WorkqueueServiceClient is the client API for WorkqueueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkqueueServiceClient interface {
	Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error)
	GetKeyState(ctx context.Context, in *GetKeyStateRequest, opts ...grpc.CallOption) (*KeyState, error)
}

type workqueueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkqueueServiceClient(cc grpc.ClientConnInterface) WorkqueueServiceClient {
	return &workqueueServiceClient{cc}
}

func (c *workqueueServiceClient) Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, WorkqueueService_Process_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workqueueServiceClient) GetKeyState(ctx context.Context, in *GetKeyStateRequest, opts ...grpc.CallOption) (*KeyState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyState)
	err := c.cc.Invoke(ctx, WorkqueueService_GetKeyState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkqueueServiceServer is the server API for WorkqueueService service.
// All implementations must embed UnimplementedWorkqueueServiceServer
// for forward compatibility.
type WorkqueueServiceServer interface {
	Process(context.Context, *ProcessRequest) (*ProcessResponse, error)
	GetKeyState(context.Context, *GetKeyStateRequest) (*KeyState, error)
	mustEmbedUnimplementedWorkqueueServiceServer()
}

// UnimplementedWorkqueueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkqueueServiceServer struct{}

func (UnimplementedWorkqueueServiceServer) Process(context.Context, *ProcessRequest) (*ProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedWorkqueueServiceServer) GetKeyState(context.Context, *GetKeyStateRequest) (*KeyState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyState not implemented")
}
func (UnimplementedWorkqueueServiceServer) mustEmbedUnimplementedWorkqueueServiceServer() {}
func (UnimplementedWorkqueueServiceServer) testEmbeddedByValue()                          {}

// UnsafeWorkqueueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkqueueServiceServer will
// result in compilation errors.
type UnsafeWorkqueueServiceServer interface {
	mustEmbedUnimplementedWorkqueueServiceServer()
}

func RegisterWorkqueueServiceServer(s grpc.ServiceRegistrar, srv WorkqueueServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkqueueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkqueueService_ServiceDesc, srv)
}

func _WorkqueueService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkqueueServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkqueueService_Process_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkqueueServiceServer).Process(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkqueueService_GetKeyState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkqueueServiceServer).GetKeyState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkqueueService_GetKeyState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkqueueServiceServer).GetKeyState(ctx, req.(*GetKeyStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkqueueService_ServiceDesc is the grpc.ServiceDesc for WorkqueueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkqueueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainguard.workqueue.WorkqueueService",
	HandlerType: (*WorkqueueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _WorkqueueService_Process_Handler,
		},
		{
			MethodName: "GetKeyState",
			Handler:    _WorkqueueService_GetKeyState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workqueue.proto",
}
