// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.1
// source: workqueue.proto

package workqueue

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WorkqueueService_Process_FullMethodName = "/chainguard.workqueue.WorkqueueService/Process"
)

// WorkqueueServiceClient is the client API for WorkqueueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkqueueServiceClient interface {
	Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error)
}

type workqueueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkqueueServiceClient(cc grpc.ClientConnInterface) WorkqueueServiceClient {
	return &workqueueServiceClient{cc}
}

func (c *workqueueServiceClient) Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error) {
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, WorkqueueService_Process_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkqueueServiceServer is the server API for WorkqueueService service.
// All implementations must embed UnimplementedWorkqueueServiceServer
// for forward compatibility
type WorkqueueServiceServer interface {
	Process(context.Context, *ProcessRequest) (*ProcessResponse, error)
	mustEmbedUnimplementedWorkqueueServiceServer()
}

// UnimplementedWorkqueueServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWorkqueueServiceServer struct {
}

func (UnimplementedWorkqueueServiceServer) Process(context.Context, *ProcessRequest) (*ProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedWorkqueueServiceServer) mustEmbedUnimplementedWorkqueueServiceServer() {}

// UnsafeWorkqueueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkqueueServiceServer will
// result in compilation errors.
type UnsafeWorkqueueServiceServer interface {
	mustEmbedUnimplementedWorkqueueServiceServer()
}

func RegisterWorkqueueServiceServer(s grpc.ServiceRegistrar, srv WorkqueueServiceServer) {
	s.RegisterService(&WorkqueueService_ServiceDesc, srv)
}

func _WorkqueueService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkqueueServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkqueueService_Process_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkqueueServiceServer).Process(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkqueueService_ServiceDesc is the grpc.ServiceDesc for WorkqueueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkqueueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainguard.workqueue.WorkqueueService",
	HandlerType: (*WorkqueueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _WorkqueueService_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workqueue.proto",
}
