issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/infra-images:pull_request
claim_pattern:
  job_workflow_ref: chainguard-dev/terraform-infra-common/.github/workflows/deprecated-repo.yaml@.*

permissions:
  pull_requests: write
